In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Problem Statemnet:  
Develop a crop recommendation system using **machine learning** that analyzes soil and environmental parameters to **suggest optimal crops for maximizing agricultural productivity.**

In [3]:
df = pd.read_csv("Crop_recommendation.csv")
df.head(10)

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice
5  69  37  42    23.058049  83.370118  7.073454  251.055000  rice
6  69  55  38    22.708838  82.639414  5.700806  271.324860  rice
7  94  53  40    20.277744  82.894086  5.718627  241.974195  rice
8  89  54  38    24.515881  83.535216  6.685346  230.446236  rice
9  68  58  38    23.223974  83.033227  6.336254  221.209196  rice

## About Dataset
N - ratio of Nitrogen content in soil  
P - ratio of Phosphorous content in soil  
K - ratio of Potassium content in soil  
temperature - temperature in degree Celsius  
humidity - relative humidity in %  
ph - ph value of the soil  
rainfall - rainfall in mm

In [4]:
pd.set_option('display.float_format', '{:.2f}'.format)
# pet.set_option('optio_name',value)

In [5]:
df.head()

    N   P   K  temperature  humidity   ph  rainfall label
0  90  42  43        20.88     82.00 6.50    202.94  rice
1  85  58  41        21.77     80.32 7.04    226.66  rice
2  60  55  44        23.00     82.32 7.84    263.96  rice
3  74  35  40        26.49     80.16 6.98    242.86  rice
4  78  42  42        20.13     81.60 7.63    262.72  rice

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

df.describe()

In [9]:
pd.set_option('display.float_format','{:.2f}'.format)

In [10]:
df.describe()

            N       P       K  temperature  humidity      ph  rainfall
count 2200.00 2200.00 2200.00      2200.00   2200.00 2200.00   2200.00
mean    50.55   53.36   48.15        25.62     71.48    6.47    103.46
std     36.92   32.99   50.65         5.06     22.26    0.77     54.96
min      0.00    5.00    5.00         8.83     14.26    3.50     20.21
25%     21.00   28.00   20.00        22.77     60.26    5.97     64.55
50%     37.00   51.00   32.00        25.60     80.47    6.43     94.87
75%     84.25   68.00   49.00        28.56     89.95    6.92    124.27
max    140.00  145.00  205.00        43.68     99.98    9.94    298.56

In [13]:
X = df.drop('label',axis=1)
y = df['label']
# axis=0 → rows
# axis=1 → columns

## Split data

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## importing models

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [22]:
lr = LogisticRegression(max_iter=200)
dt = DecisionTreeClassifier()
rf = RandomForestClassifier()

In [23]:
lr.fit(X_train , y_train)
dt.fit(X_train , y_train)
rf.fit(X_train , y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 200 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=200).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

RandomForestClassifier()

## Comparing Accuracy

In [25]:
from sklearn.metrics import accuracy_score
y_pred_lr = lr.predict(X_test)
y_pred_dt = dt.predict(X_test)
y_pred_rf = rf.predict(X_test)

print("Accuray Score:")
print("Logistic Regression :",accuracy_score(y_test,y_pred_lr))
print("Decision Tree :",accuracy_score(y_test,y_pred_dt))
print("Random Forest :",accuracy_score(y_test,y_pred_rf))

Accuray Score:
Logistic Regression : 0.9477272727272728
Decision Tree : 0.9886363636363636
Random Forest : 0.9931818181818182

#### we can see that **Random Forest** have the highest accuracy among other two models.
Because the dataset is clean and well-separated, even simple models perform optimally. Random Forest doesn’t significantly improve over Decision Tree in this case.

In [28]:
N = float(input("Enter Nitrogen (N): "))
P = float(input("Enter Phosphorus (P): "))
K = float(input("Enter Potassium (K): "))
temp = float(input("Enter Temperature: "))
humidity = float(input("Enter Humidity: "))
ph = float(input("Enter pH: "))
rainfall = float(input("Enter Rainfall: "))
sample = [[N,P,K,temp,humidity,ph,rainfall]]

pred = rf.predict(sample)
print("Recomended Crop : ",pred[0])

Enter Nitrogen (N):  90
Enter Phosphorus (P):  78
Enter Potassium (K):  88
Enter Temperature:  57
Enter Humidity:  56
Enter pH:  89
Enter Rainfall:  99

Recomended Crop :  banana

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(